//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 11:22:11 AM IST 
//


package com.vidyo.parser.xsd.vmconfig;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vidyo.parser.xsd.vmconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName("http://www.vidyo.com/VMConfigParser.xsd", "Config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vidyo.parser.xsd.vmconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VpURI }
     * 
     */
    public VpURI createVpURI() {
        return new VpURI();
    }

    /**
     * Create an instance of {@link DatabaseConfigType }
     * 
     */
    public DatabaseConfigType createDatabaseConfigType() {
        return new DatabaseConfigType();
    }

    /**
     * Create an instance of {@link SOAPListenAddressType }
     * 
     */
    public SOAPListenAddressType createSOAPListenAddressType() {
        return new SOAPListenAddressType();
    }

    /**
     * Create an instance of {@link EMCPListenAddressType }
     * 
     */
    public EMCPListenAddressType createEMCPListenAddressType() {
        return new EMCPListenAddressType();
    }

    /**
     * Create an instance of {@link VidyoPortalConnectAddressType }
     * 
     */
    public VidyoPortalConnectAddressType createVidyoPortalConnectAddressType() {
        return new VidyoPortalConnectAddressType();
    }

    /**
     * Create an instance of {@link VMConfigType }
     * 
     */
    public VMConfigType createVMConfigType() {
        return new VMConfigType();
    }

    /**
     * Create an instance of {@link RMCPListenAddressType }
     * 
     */
    public RMCPListenAddressType createRMCPListenAddressType() {
        return new RMCPListenAddressType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VMConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vidyo.com/VMConfigParser.xsd", name = "Config")
    public JAXBElement<VMConfigType> createConfig(VMConfigType value) {
        return new JAXBElement<VMConfigType>(_Config_QNAME, VMConfigType.class, null, value);
    }

}
