//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 11:22:11 AM IST 
//


package com.vidyo.parser.xsd.vmconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VMConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VMConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SOAPAddressList" type="{http://www.vidyo.com/VMConfigParser.xsd}SOAPListenAddressType"/>
 *         &lt;element name="EMCPAddressList" type="{http://www.vidyo.com/VMConfigParser.xsd}EMCPListenAddressType"/>
 *         &lt;element name="RMCPAddressList" type="{http://www.vidyo.com/VMConfigParser.xsd}RMCPListenAddressType"/>
 *         &lt;element name="VidyoPortalAddressList" type="{http://www.vidyo.com/VMConfigParser.xsd}VidyoPortalConnectAddressType"/>
 *         &lt;element name="SecurityEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DatabaseConfig" type="{http://www.vidyo.com/VMConfigParser.xsd}DatabaseConfigType"/>
 *         &lt;element name="LogFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LogLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxLogFileSizeKB" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="LogFileHistoryDays" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="Stat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfThreads" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="SignalingPrecedence" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VMConfigType", propOrder = {
    "documentVersion",
    "ipAddress",
    "soapAddressList",
    "emcpAddressList",
    "rmcpAddressList",
    "vidyoPortalAddressList",
    "securityEnabled",
    "databaseConfig",
    "logFileName",
    "logLevel",
    "maxLogFileSizeKB",
    "logFileHistoryDays",
    "stat",
    "numberOfThreads",
    "signalingPrecedence"
})
public class VMConfigType {

    @XmlElement(name = "DocumentVersion", required = true)
    protected String documentVersion;
    @XmlElement(name = "IPAddress")
    protected String ipAddress;
    @XmlElement(name = "SOAPAddressList", required = true)
    protected SOAPListenAddressType soapAddressList;
    @XmlElement(name = "EMCPAddressList", required = true)
    protected EMCPListenAddressType emcpAddressList;
    @XmlElement(name = "RMCPAddressList", required = true)
    protected RMCPListenAddressType rmcpAddressList;
    @XmlElement(name = "VidyoPortalAddressList", required = true)
    protected VidyoPortalConnectAddressType vidyoPortalAddressList;
    @XmlElement(name = "SecurityEnabled")
    protected Boolean securityEnabled;
    @XmlElement(name = "DatabaseConfig", required = true)
    protected DatabaseConfigType databaseConfig;
    @XmlElement(name = "LogFileName")
    protected String logFileName;
    @XmlElement(name = "LogLevel")
    protected String logLevel;
    @XmlElement(name = "MaxLogFileSizeKB")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxLogFileSizeKB;
    @XmlElement(name = "LogFileHistoryDays")
    @XmlSchemaType(name = "unsignedInt")
    protected Long logFileHistoryDays;
    @XmlElement(name = "Stat", required = true)
    protected String stat;
    @XmlElement(name = "NumberOfThreads")
    @XmlSchemaType(name = "unsignedInt")
    protected long numberOfThreads;
    @XmlElement(name = "SignalingPrecedence")
    @XmlSchemaType(name = "unsignedInt")
    protected Long signalingPrecedence;

    /**
     * Gets the value of the documentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentVersion() {
        return documentVersion;
    }

    /**
     * Sets the value of the documentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentVersion(String value) {
        this.documentVersion = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the soapAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link SOAPListenAddressType }
     *     
     */
    public SOAPListenAddressType getSOAPAddressList() {
        return soapAddressList;
    }

    /**
     * Sets the value of the soapAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOAPListenAddressType }
     *     
     */
    public void setSOAPAddressList(SOAPListenAddressType value) {
        this.soapAddressList = value;
    }

    /**
     * Gets the value of the emcpAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link EMCPListenAddressType }
     *     
     */
    public EMCPListenAddressType getEMCPAddressList() {
        return emcpAddressList;
    }

    /**
     * Sets the value of the emcpAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMCPListenAddressType }
     *     
     */
    public void setEMCPAddressList(EMCPListenAddressType value) {
        this.emcpAddressList = value;
    }

    /**
     * Gets the value of the rmcpAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link RMCPListenAddressType }
     *     
     */
    public RMCPListenAddressType getRMCPAddressList() {
        return rmcpAddressList;
    }

    /**
     * Sets the value of the rmcpAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RMCPListenAddressType }
     *     
     */
    public void setRMCPAddressList(RMCPListenAddressType value) {
        this.rmcpAddressList = value;
    }

    /**
     * Gets the value of the vidyoPortalAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link VidyoPortalConnectAddressType }
     *     
     */
    public VidyoPortalConnectAddressType getVidyoPortalAddressList() {
        return vidyoPortalAddressList;
    }

    /**
     * Sets the value of the vidyoPortalAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VidyoPortalConnectAddressType }
     *     
     */
    public void setVidyoPortalAddressList(VidyoPortalConnectAddressType value) {
        this.vidyoPortalAddressList = value;
    }

    /**
     * Gets the value of the securityEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSecurityEnabled() {
        return securityEnabled;
    }

    /**
     * Sets the value of the securityEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSecurityEnabled(Boolean value) {
        this.securityEnabled = value;
    }

    /**
     * Gets the value of the databaseConfig property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseConfigType }
     *     
     */
    public DatabaseConfigType getDatabaseConfig() {
        return databaseConfig;
    }

    /**
     * Sets the value of the databaseConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseConfigType }
     *     
     */
    public void setDatabaseConfig(DatabaseConfigType value) {
        this.databaseConfig = value;
    }

    /**
     * Gets the value of the logFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogFileName() {
        return logFileName;
    }

    /**
     * Sets the value of the logFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogFileName(String value) {
        this.logFileName = value;
    }

    /**
     * Gets the value of the logLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogLevel() {
        return logLevel;
    }

    /**
     * Sets the value of the logLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogLevel(String value) {
        this.logLevel = value;
    }

    /**
     * Gets the value of the maxLogFileSizeKB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxLogFileSizeKB() {
        return maxLogFileSizeKB;
    }

    /**
     * Sets the value of the maxLogFileSizeKB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxLogFileSizeKB(Long value) {
        this.maxLogFileSizeKB = value;
    }

    /**
     * Gets the value of the logFileHistoryDays property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLogFileHistoryDays() {
        return logFileHistoryDays;
    }

    /**
     * Sets the value of the logFileHistoryDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLogFileHistoryDays(Long value) {
        this.logFileHistoryDays = value;
    }

    /**
     * Gets the value of the stat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStat() {
        return stat;
    }

    /**
     * Sets the value of the stat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStat(String value) {
        this.stat = value;
    }

    /**
     * Gets the value of the numberOfThreads property.
     * 
     */
    public long getNumberOfThreads() {
        return numberOfThreads;
    }

    /**
     * Sets the value of the numberOfThreads property.
     * 
     */
    public void setNumberOfThreads(long value) {
        this.numberOfThreads = value;
    }

    /**
     * Gets the value of the signalingPrecedence property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSignalingPrecedence() {
        return signalingPrecedence;
    }

    /**
     * Sets the value of the signalingPrecedence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSignalingPrecedence(Long value) {
        this.signalingPrecedence = value;
    }

}
