//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.18 at 02:20:00 PM EDT 
//


package com.vidyo.parser.xml.cloudconfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BandwidthMapType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BandwidthMapType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BandwidthMapElement" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FromRouterGroupID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ToRouterGroupID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="WeightedBandwidth">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="100"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BandwidthMapType", propOrder = {
    "bandwidthMapElement"
})
public class BandwidthMapType {

    @XmlElement(name = "BandwidthMapElement")
    protected List<BandwidthMapType.BandwidthMapElement> bandwidthMapElement;

    /**
     * Gets the value of the bandwidthMapElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bandwidthMapElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBandwidthMapElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BandwidthMapType.BandwidthMapElement }
     * 
     * 
     */
    public List<BandwidthMapType.BandwidthMapElement> getBandwidthMapElement() {
        if (bandwidthMapElement == null) {
            bandwidthMapElement = new ArrayList<BandwidthMapType.BandwidthMapElement>();
        }
        return this.bandwidthMapElement;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FromRouterGroupID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ToRouterGroupID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="WeightedBandwidth">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="100"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fromRouterGroupID",
        "toRouterGroupID",
        "weightedBandwidth"
    })
    public static class BandwidthMapElement {

        @XmlElement(name = "FromRouterGroupID", required = true)
        protected String fromRouterGroupID;
        @XmlElement(name = "ToRouterGroupID", required = true)
        protected String toRouterGroupID;
        @XmlElement(name = "WeightedBandwidth")
        protected long weightedBandwidth;

        /**
         * Gets the value of the fromRouterGroupID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromRouterGroupID() {
            return fromRouterGroupID;
        }

        /**
         * Sets the value of the fromRouterGroupID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromRouterGroupID(String value) {
            this.fromRouterGroupID = value;
        }

        /**
         * Gets the value of the toRouterGroupID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToRouterGroupID() {
            return toRouterGroupID;
        }

        /**
         * Sets the value of the toRouterGroupID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToRouterGroupID(String value) {
            this.toRouterGroupID = value;
        }

        /**
         * Gets the value of the weightedBandwidth property.
         * 
         */
        public long getWeightedBandwidth() {
            return weightedBandwidth;
        }

        /**
         * Sets the value of the weightedBandwidth property.
         * 
         */
        public void setWeightedBandwidth(long value) {
            this.weightedBandwidth = value;
        }

    }

}
