//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.18 at 02:20:00 PM EDT 
//


package com.vidyo.parser.xml.cloudconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BasicRuleSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicRuleSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="BasicAnd" type="{}BasicAndType"/>
 *           &lt;element name="BasicOr" type="{}BasicOrType"/>
 *           &lt;element name="BasicNot" type="{}BasicNotType"/>
 *           &lt;element name="BasicRule" type="{}BasicRuleType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicRuleSet", propOrder = {
    "basicAnd",
    "basicOr",
    "basicNot",
    "basicRule"
})
public class BasicRuleSet {

    @XmlElement(name = "BasicAnd")
    protected BasicAndType basicAnd;
    @XmlElement(name = "BasicOr")
    protected BasicOrType basicOr;
    @XmlElement(name = "BasicNot")
    protected BasicNotType basicNot;
    @XmlElement(name = "BasicRule")
    protected BasicRuleType basicRule;

    /**
     * Gets the value of the basicAnd property.
     * 
     * @return
     *     possible object is
     *     {@link BasicAndType }
     *     
     */
    public BasicAndType getBasicAnd() {
        return basicAnd;
    }

    /**
     * Sets the value of the basicAnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicAndType }
     *     
     */
    public void setBasicAnd(BasicAndType value) {
        this.basicAnd = value;
    }

    /**
     * Gets the value of the basicOr property.
     * 
     * @return
     *     possible object is
     *     {@link BasicOrType }
     *     
     */
    public BasicOrType getBasicOr() {
        return basicOr;
    }

    /**
     * Sets the value of the basicOr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicOrType }
     *     
     */
    public void setBasicOr(BasicOrType value) {
        this.basicOr = value;
    }

    /**
     * Gets the value of the basicNot property.
     * 
     * @return
     *     possible object is
     *     {@link BasicNotType }
     *     
     */
    public BasicNotType getBasicNot() {
        return basicNot;
    }

    /**
     * Sets the value of the basicNot property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicNotType }
     *     
     */
    public void setBasicNot(BasicNotType value) {
        this.basicNot = value;
    }

    /**
     * Gets the value of the basicRule property.
     * 
     * @return
     *     possible object is
     *     {@link BasicRuleType }
     *     
     */
    public BasicRuleType getBasicRule() {
        return basicRule;
    }

    /**
     * Sets the value of the basicRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicRuleType }
     *     
     */
    public void setBasicRule(BasicRuleType value) {
        this.basicRule = value;
    }

}
