//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 11:56:10 AM EDT 
//


package com.vidyo.parser.xml.cloudconfig;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vidyo.parser.xml.cloudconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NetworkConfig_QNAME = new QName("", "NetworkConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vidyo.parser.xml.cloudconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BandwidthMapType.BandwidthMapElement }
     * 
     */
    public BandwidthMapType.BandwidthMapElement createBandwidthMapTypeBandwidthMapElement() {
        return new BandwidthMapType.BandwidthMapElement();
    }

    /**
     * Create an instance of {@link NotType }
     * 
     */
    public NotType createNotType() {
        return new NotType();
    }

    /**
     * Create an instance of {@link BandwidthMapType }
     * 
     */
    public BandwidthMapType createBandwidthMapType() {
        return new BandwidthMapType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link GreaterThanOrEqualToType }
     * 
     */
    public GreaterThanOrEqualToType createGreaterThanOrEqualToType() {
        return new GreaterThanOrEqualToType();
    }

    /**
     * Create an instance of {@link OrType }
     * 
     */
    public OrType createOrType() {
        return new OrType();
    }

    /**
     * Create an instance of {@link IPV4AddressRangeType }
     * 
     */
    public IPV4AddressRangeType createIPV4AddressRangeType() {
        return new IPV4AddressRangeType();
    }

    /**
     * Create an instance of {@link BasicOrType }
     * 
     */
    public BasicOrType createBasicOrType() {
        return new BasicOrType();
    }

    /**
     * Create an instance of {@link GroupType.NetworkElements }
     * 
     */
    public GroupType.NetworkElements createGroupTypeNetworkElements() {
        return new GroupType.NetworkElements();
    }

    /**
     * Create an instance of {@link ListMemberType }
     * 
     */
    public ListMemberType createListMemberType() {
        return new ListMemberType();
    }

    /**
     * Create an instance of {@link CategoriesType }
     * 
     */
    public CategoriesType createCategoriesType() {
        return new CategoriesType();
    }

    /**
     * Create an instance of {@link LocationType.PrioritizedGroupLists }
     * 
     */
    public LocationType.PrioritizedGroupLists createLocationTypePrioritizedGroupLists() {
        return new LocationType.PrioritizedGroupLists();
    }

    /**
     * Create an instance of {@link Candidates }
     * 
     */
    public Candidates createCandidates() {
        return new Candidates();
    }

    /**
     * Create an instance of {@link BasicAndType }
     * 
     */
    public BasicAndType createBasicAndType() {
        return new BasicAndType();
    }

    /**
     * Create an instance of {@link RuleSetType }
     * 
     */
    public RuleSetType createRuleSetType() {
        return new RuleSetType();
    }

    /**
     * Create an instance of {@link GreaterThanType }
     * 
     */
    public GreaterThanType createGreaterThanType() {
        return new GreaterThanType();
    }

    /**
     * Create an instance of {@link IPV4SubnetType }
     * 
     */
    public IPV4SubnetType createIPV4SubnetType() {
        return new IPV4SubnetType();
    }

    /**
     * Create an instance of {@link BasicRuleSet }
     * 
     */
    public BasicRuleSet createBasicRuleSet() {
        return new BasicRuleSet();
    }

    /**
     * Create an instance of {@link AndType }
     * 
     */
    public AndType createAndType() {
        return new AndType();
    }

    /**
     * Create an instance of {@link NetworkConfigType }
     * 
     */
    public NetworkConfigType createNetworkConfigType() {
        return new NetworkConfigType();
    }

    /**
     * Create an instance of {@link BasicRuleType }
     * 
     */
    public BasicRuleType createBasicRuleType() {
        return new BasicRuleType();
    }

    /**
     * Create an instance of {@link LocationType.PrioritizedGroupLists.GroupList }
     * 
     */
    public LocationType.PrioritizedGroupLists.GroupList createLocationTypePrioritizedGroupListsGroupList() {
        return new LocationType.PrioritizedGroupLists.GroupList();
    }

    /**
     * Create an instance of {@link NetworkElement }
     * 
     */
    public NetworkElement createNetworkElement() {
        return new NetworkElement();
    }

    /**
     * Create an instance of {@link LessThanType }
     * 
     */
    public LessThanType createLessThanType() {
        return new LessThanType();
    }

    /**
     * Create an instance of {@link EqualToType }
     * 
     */
    public EqualToType createEqualToType() {
        return new EqualToType();
    }

    /**
     * Create an instance of {@link LessThanOrEqualToType }
     * 
     */
    public LessThanOrEqualToType createLessThanOrEqualToType() {
        return new LessThanOrEqualToType();
    }

    /**
     * Create an instance of {@link BasicNotType }
     * 
     */
    public BasicNotType createBasicNotType() {
        return new BasicNotType();
    }

    /**
     * Create an instance of {@link NetworkElement.SCIPAddressList }
     * 
     */
    public NetworkElement.SCIPAddressList createNetworkElementSCIPAddressList() {
        return new NetworkElement.SCIPAddressList();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NetworkConfig")
    public JAXBElement<NetworkConfigType> createNetworkConfig(NetworkConfigType value) {
        return new JAXBElement<NetworkConfigType>(_NetworkConfig_QNAME, NetworkConfigType.class, null, value);
    }

}
