//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 11:05:46 AM EDT 
//


package com.vidyo.parser.xml.vrconfig;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vidyo.parser.xml.vrconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName("", "Config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vidyo.parser.xml.vrconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VRConfigType.ListenVMList }
     * 
     */
    public VRConfigType.ListenVMList createVRConfigTypeListenVMList() {
        return new VRConfigType.ListenVMList();
    }

    /**
     * Create an instance of {@link VRConfigType.MediaAddressMap }
     * 
     */
    public VRConfigType.MediaAddressMap createVRConfigTypeMediaAddressMap() {
        return new VRConfigType.MediaAddressMap();
    }

    /**
     * Create an instance of {@link VRConfigType.ConnectVMList }
     * 
     */
    public VRConfigType.ConnectVMList createVRConfigTypeConnectVMList() {
        return new VRConfigType.ConnectVMList();
    }

    /**
     * Create an instance of {@link VRConfigType }
     * 
     */
    public VRConfigType createVRConfigType() {
        return new VRConfigType();
    }

    /**
     * Create an instance of {@link VrURI }
     * 
     */
    public VrURI createVrURI() {
        return new VrURI();
    }

    /**
     * Create an instance of {@link MediaStreamPrecedenceType }
     * 
     */
    public MediaStreamPrecedenceType createMediaStreamPrecedenceType() {
        return new MediaStreamPrecedenceType();
    }

    /**
     * Create an instance of {@link VRConfigType.MediaPortRange }
     * 
     */
    public VRConfigType.MediaPortRange createVRConfigTypeMediaPortRange() {
        return new VRConfigType.MediaPortRange();
    }

    /**
     * Create an instance of {@link VRConfigType.CMCPAddressList }
     * 
     */
    public VRConfigType.CMCPAddressList createVRConfigTypeCMCPAddressList() {
        return new VRConfigType.CMCPAddressList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VRConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Config")
    public JAXBElement<VRConfigType> createConfig(VRConfigType value) {
        return new JAXBElement<VRConfigType>(_Config_QNAME, VRConfigType.class, null, value);
    }

}
