//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.19 at 05:54:23 PM EDT 
//


package com.vidyo.parser.xml.vrconfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VRConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VRConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RouterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CMCPAddressList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CMCPListenAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="VidyoManagerAccess" type="{}VMAccessType"/>
 *         &lt;element name="ListenVMList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ListenVM" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ConnectVMList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ConnectVM" type="{}vrURI" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MediaAddressMap" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LocalAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RemoteAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StunServerAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MediaPortRange" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Start" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="End" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SecurityEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="VideoPrecedence" type="{}MediaStreamPrecedenceType" minOccurs="0"/>
 *         &lt;element name="AudioPrecedence" type="{}MediaStreamPrecedenceType" minOccurs="0"/>
 *         &lt;element name="AppPrecedence" type="{}MediaStreamPrecedenceType" minOccurs="0"/>
 *         &lt;element name="LogFileHistoryDays" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="LogFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LogLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxLogFileSizeKB" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="Stat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfThreads" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VRConfigType", propOrder = {
    "documentVersion",
    "routerName",
    "cmcpAddressList",
    "vidyoManagerAccess",
    "listenVMList",
    "connectVMList",
    "mediaAddressMap",
    "stunServerAddress",
    "mediaPortRange",
    "securityEnabled",
    "videoPrecedence",
    "audioPrecedence",
    "appPrecedence",
    "logFileHistoryDays",
    "logFileName",
    "logLevel",
    "maxLogFileSizeKB",
    "stat",
    "numberOfThreads"
})
public class VRConfigType {

    @XmlElement(name = "DocumentVersion", required = true)
    protected String documentVersion;
    @XmlElement(name = "RouterName", required = true)
    protected String routerName;
    @XmlElement(name = "CMCPAddressList", required = true)
    protected VRConfigType.CMCPAddressList cmcpAddressList;
    @XmlElement(name = "VidyoManagerAccess", required = true)
    protected VMAccessType vidyoManagerAccess;
    @XmlElement(name = "ListenVMList", required = true)
    protected VRConfigType.ListenVMList listenVMList;
    @XmlElement(name = "ConnectVMList", required = true)
    protected VRConfigType.ConnectVMList connectVMList;
    @XmlElement(name = "MediaAddressMap")
    protected List<VRConfigType.MediaAddressMap> mediaAddressMap;
    @XmlElement(name = "StunServerAddress")
    protected String stunServerAddress;
    @XmlElement(name = "MediaPortRange")
    protected VRConfigType.MediaPortRange mediaPortRange;
    @XmlElement(name = "SecurityEnabled")
    protected Boolean securityEnabled;
    @XmlElement(name = "VideoPrecedence")
    protected MediaStreamPrecedenceType videoPrecedence;
    @XmlElement(name = "AudioPrecedence")
    protected MediaStreamPrecedenceType audioPrecedence;
    @XmlElement(name = "AppPrecedence")
    protected MediaStreamPrecedenceType appPrecedence;
    @XmlElement(name = "LogFileHistoryDays")
    @XmlSchemaType(name = "unsignedInt")
    protected Long logFileHistoryDays;
    @XmlElement(name = "LogFileName")
    protected String logFileName;
    @XmlElement(name = "LogLevel")
    protected String logLevel;
    @XmlElement(name = "MaxLogFileSizeKB")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxLogFileSizeKB;
    @XmlElement(name = "Stat", required = true)
    protected String stat;
    @XmlElement(name = "NumberOfThreads")
    @XmlSchemaType(name = "unsignedInt")
    protected long numberOfThreads;

    /**
     * Gets the value of the documentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentVersion() {
        return documentVersion;
    }

    /**
     * Sets the value of the documentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentVersion(String value) {
        this.documentVersion = value;
    }

    /**
     * Gets the value of the routerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouterName() {
        return routerName;
    }

    /**
     * Sets the value of the routerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouterName(String value) {
        this.routerName = value;
    }

    /**
     * Gets the value of the cmcpAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link VRConfigType.CMCPAddressList }
     *     
     */
    public VRConfigType.CMCPAddressList getCMCPAddressList() {
        return cmcpAddressList;
    }

    /**
     * Sets the value of the cmcpAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VRConfigType.CMCPAddressList }
     *     
     */
    public void setCMCPAddressList(VRConfigType.CMCPAddressList value) {
        this.cmcpAddressList = value;
    }

    /**
     * Gets the value of the vidyoManagerAccess property.
     * 
     * @return
     *     possible object is
     *     {@link VMAccessType }
     *     
     */
    public VMAccessType getVidyoManagerAccess() {
        return vidyoManagerAccess;
    }

    /**
     * Sets the value of the vidyoManagerAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link VMAccessType }
     *     
     */
    public void setVidyoManagerAccess(VMAccessType value) {
        this.vidyoManagerAccess = value;
    }

    /**
     * Gets the value of the listenVMList property.
     * 
     * @return
     *     possible object is
     *     {@link VRConfigType.ListenVMList }
     *     
     */
    public VRConfigType.ListenVMList getListenVMList() {
        return listenVMList;
    }

    /**
     * Sets the value of the listenVMList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VRConfigType.ListenVMList }
     *     
     */
    public void setListenVMList(VRConfigType.ListenVMList value) {
        this.listenVMList = value;
    }

    /**
     * Gets the value of the connectVMList property.
     * 
     * @return
     *     possible object is
     *     {@link VRConfigType.ConnectVMList }
     *     
     */
    public VRConfigType.ConnectVMList getConnectVMList() {
        return connectVMList;
    }

    /**
     * Sets the value of the connectVMList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VRConfigType.ConnectVMList }
     *     
     */
    public void setConnectVMList(VRConfigType.ConnectVMList value) {
        this.connectVMList = value;
    }

    /**
     * Gets the value of the mediaAddressMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mediaAddressMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMediaAddressMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VRConfigType.MediaAddressMap }
     * 
     * 
     */
    public List<VRConfigType.MediaAddressMap> getMediaAddressMap() {
        if (mediaAddressMap == null) {
            mediaAddressMap = new ArrayList<VRConfigType.MediaAddressMap>();
        }
        return this.mediaAddressMap;
    }

    /**
     * Gets the value of the stunServerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStunServerAddress() {
        return stunServerAddress;
    }

    /**
     * Sets the value of the stunServerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStunServerAddress(String value) {
        this.stunServerAddress = value;
    }

    /**
     * Gets the value of the mediaPortRange property.
     * 
     * @return
     *     possible object is
     *     {@link VRConfigType.MediaPortRange }
     *     
     */
    public VRConfigType.MediaPortRange getMediaPortRange() {
        return mediaPortRange;
    }

    /**
     * Sets the value of the mediaPortRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link VRConfigType.MediaPortRange }
     *     
     */
    public void setMediaPortRange(VRConfigType.MediaPortRange value) {
        this.mediaPortRange = value;
    }

    /**
     * Gets the value of the securityEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSecurityEnabled() {
        return securityEnabled;
    }

    /**
     * Sets the value of the securityEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSecurityEnabled(Boolean value) {
        this.securityEnabled = value;
    }

    /**
     * Gets the value of the videoPrecedence property.
     * 
     * @return
     *     possible object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public MediaStreamPrecedenceType getVideoPrecedence() {
        return videoPrecedence;
    }

    /**
     * Sets the value of the videoPrecedence property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public void setVideoPrecedence(MediaStreamPrecedenceType value) {
        this.videoPrecedence = value;
    }

    /**
     * Gets the value of the audioPrecedence property.
     * 
     * @return
     *     possible object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public MediaStreamPrecedenceType getAudioPrecedence() {
        return audioPrecedence;
    }

    /**
     * Sets the value of the audioPrecedence property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public void setAudioPrecedence(MediaStreamPrecedenceType value) {
        this.audioPrecedence = value;
    }

    /**
     * Gets the value of the appPrecedence property.
     * 
     * @return
     *     possible object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public MediaStreamPrecedenceType getAppPrecedence() {
        return appPrecedence;
    }

    /**
     * Sets the value of the appPrecedence property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public void setAppPrecedence(MediaStreamPrecedenceType value) {
        this.appPrecedence = value;
    }

    /**
     * Gets the value of the logFileHistoryDays property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLogFileHistoryDays() {
        return logFileHistoryDays;
    }

    /**
     * Sets the value of the logFileHistoryDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLogFileHistoryDays(Long value) {
        this.logFileHistoryDays = value;
    }

    /**
     * Gets the value of the logFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogFileName() {
        return logFileName;
    }

    /**
     * Sets the value of the logFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogFileName(String value) {
        this.logFileName = value;
    }

    /**
     * Gets the value of the logLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogLevel() {
        return logLevel;
    }

    /**
     * Sets the value of the logLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogLevel(String value) {
        this.logLevel = value;
    }

    /**
     * Gets the value of the maxLogFileSizeKB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxLogFileSizeKB() {
        return maxLogFileSizeKB;
    }

    /**
     * Sets the value of the maxLogFileSizeKB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxLogFileSizeKB(Long value) {
        this.maxLogFileSizeKB = value;
    }

    /**
     * Gets the value of the stat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStat() {
        return stat;
    }

    /**
     * Sets the value of the stat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStat(String value) {
        this.stat = value;
    }

    /**
     * Gets the value of the numberOfThreads property.
     * 
     */
    public long getNumberOfThreads() {
        return numberOfThreads;
    }

    /**
     * Sets the value of the numberOfThreads property.
     * 
     */
    public void setNumberOfThreads(long value) {
        this.numberOfThreads = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CMCPListenAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cmcpListenAddress"
    })
    public static class CMCPAddressList {

        @XmlElement(name = "CMCPListenAddress", required = true)
        protected List<String> cmcpListenAddress;

        /**
         * Gets the value of the cmcpListenAddress property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cmcpListenAddress property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCMCPListenAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCMCPListenAddress() {
            if (cmcpListenAddress == null) {
                cmcpListenAddress = new ArrayList<String>();
            }
            return this.cmcpListenAddress;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ConnectVM" type="{}vrURI" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "connectVM"
    })
    public static class ConnectVMList {

        @XmlElement(name = "ConnectVM")
        protected List<VrURI> connectVM;

        /**
         * Gets the value of the connectVM property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the connectVM property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConnectVM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VrURI }
         * 
         * 
         */
        public List<VrURI> getConnectVM() {
            if (connectVM == null) {
                connectVM = new ArrayList<VrURI>();
            }
            return this.connectVM;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ListenVM" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listenVM"
    })
    public static class ListenVMList {

        @XmlElement(name = "ListenVM")
        protected List<String> listenVM;

        /**
         * Gets the value of the listenVM property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the listenVM property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getListenVM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getListenVM() {
            if (listenVM == null) {
                listenVM = new ArrayList<String>();
            }
            return this.listenVM;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LocalAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RemoteAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "localAddress",
        "remoteAddress"
    })
    public static class MediaAddressMap {

        @XmlElement(name = "LocalAddress", required = true)
        protected String localAddress;
        @XmlElement(name = "RemoteAddress", required = true)
        protected String remoteAddress;

        /**
         * Gets the value of the localAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalAddress() {
            return localAddress;
        }

        /**
         * Sets the value of the localAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalAddress(String value) {
            this.localAddress = value;
        }

        /**
         * Gets the value of the remoteAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemoteAddress() {
            return remoteAddress;
        }

        /**
         * Sets the value of the remoteAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemoteAddress(String value) {
            this.remoteAddress = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Start" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="End" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "start",
        "end"
    })
    public static class MediaPortRange {

        @XmlElement(name = "Start")
        @XmlSchemaType(name = "unsignedInt")
        protected long start;
        @XmlElement(name = "End")
        @XmlSchemaType(name = "unsignedInt")
        protected long end;

        /**
         * Gets the value of the start property.
         * 
         */
        public long getStart() {
            return start;
        }

        /**
         * Sets the value of the start property.
         * 
         */
        public void setStart(long value) {
            this.start = value;
        }

        /**
         * Gets the value of the end property.
         * 
         */
        public long getEnd() {
            return end;
        }

        /**
         * Sets the value of the end property.
         * 
         */
        public void setEnd(long value) {
            this.end = value;
        }

    }

}
