/**
 * 
 */
package com.vidyo.db.transaction;

import com.vidyo.bo.transaction.TransactionFilter;
import com.vidyo.bo.transaction.TransactionHistory;

import java.util.List;

/**
 * @author Ganesh
 *
 */
public interface TransactionDao {
	
	/**
	 * Inserts a single Transaction History record in to the TransactionHistory
	 * table
	 * 
	 * @param transactionHistory
	 *            Business Object holding the transaction data
	 * @return transactionID autogenerated Identifier from the Database
	 */
	public int addTransactionHistory(TransactionHistory transactionHistory);
	
	public List<TransactionHistory> getTransactionHistoryForPeriod(TransactionFilter filter);
    public long  deleteTransactionHistoryForPeriod();
	public int getTransactionHistoryCountBetweenDates(TransactionFilter filter);
	public List<TransactionHistory> getTransactionHistoryBetweenDates(TransactionFilter filter);
}
