//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.08 at 10:58:54 AM EDT 
//


package com.vidyo.parser.xsd.vr2config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MediaStreamPrecedenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaStreamPrecedenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LowPrioDSCPBits" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="MedPrioDSCPBits" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="HighPrioDSCPBits" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaStreamPrecedenceType", propOrder = {
    "lowPrioDSCPBits",
    "medPrioDSCPBits",
    "highPrioDSCPBits"
})
public class MediaStreamPrecedenceType {

    @XmlElement(name = "LowPrioDSCPBits")
    @XmlSchemaType(name = "unsignedInt")
    protected long lowPrioDSCPBits;
    @XmlElement(name = "MedPrioDSCPBits")
    @XmlSchemaType(name = "unsignedInt")
    protected long medPrioDSCPBits;
    @XmlElement(name = "HighPrioDSCPBits")
    @XmlSchemaType(name = "unsignedInt")
    protected long highPrioDSCPBits;

    /**
     * Gets the value of the lowPrioDSCPBits property.
     * 
     */
    public long getLowPrioDSCPBits() {
        return lowPrioDSCPBits;
    }

    /**
     * Sets the value of the lowPrioDSCPBits property.
     * 
     */
    public void setLowPrioDSCPBits(long value) {
        this.lowPrioDSCPBits = value;
    }

    /**
     * Gets the value of the medPrioDSCPBits property.
     * 
     */
    public long getMedPrioDSCPBits() {
        return medPrioDSCPBits;
    }

    /**
     * Sets the value of the medPrioDSCPBits property.
     * 
     */
    public void setMedPrioDSCPBits(long value) {
        this.medPrioDSCPBits = value;
    }

    /**
     * Gets the value of the highPrioDSCPBits property.
     * 
     */
    public long getHighPrioDSCPBits() {
        return highPrioDSCPBits;
    }

    /**
     * Sets the value of the highPrioDSCPBits property.
     * 
     */
    public void setHighPrioDSCPBits(long value) {
        this.highPrioDSCPBits = value;
    }

}
