//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.08 at 10:58:54 AM EDT 
//


package com.vidyo.parser.xsd.vr2config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vidyo.parser.xsd.vr2config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName("http://www.vidyo.com/vr2configparser.xsd", "Config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vidyo.parser.xsd.vr2config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConnectVMListType }
     * 
     */
    public ConnectVMListType createConnectVMListType() {
        return new ConnectVMListType();
    }

    /**
     * Create an instance of {@link VrURI }
     * 
     */
    public VrURI createVrURI() {
        return new VrURI();
    }

    /**
     * Create an instance of {@link CMCPAddressListType }
     * 
     */
    public CMCPAddressListType createCMCPAddressListType() {
        return new CMCPAddressListType();
    }

    /**
     * Create an instance of {@link MediaStreamPrecedenceType }
     * 
     */
    public MediaStreamPrecedenceType createMediaStreamPrecedenceType() {
        return new MediaStreamPrecedenceType();
    }

    /**
     * Create an instance of {@link MediaPortRangeType }
     * 
     */
    public MediaPortRangeType createMediaPortRangeType() {
        return new MediaPortRangeType();
    }

    /**
     * Create an instance of {@link VRConfigType }
     * 
     */
    public VRConfigType createVRConfigType() {
        return new VRConfigType();
    }

    /**
     * Create an instance of {@link MediaAddressMapType }
     * 
     */
    public MediaAddressMapType createMediaAddressMapType() {
        return new MediaAddressMapType();
    }

    /**
     * Create an instance of {@link ListenVMListType }
     * 
     */
    public ListenVMListType createListenVMListType() {
        return new ListenVMListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VRConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vidyo.com/vr2configparser.xsd", name = "Config")
    public JAXBElement<VRConfigType> createConfig(VRConfigType value) {
        return new JAXBElement<VRConfigType>(_Config_QNAME, VRConfigType.class, null, value);
    }

}
