//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.08 at 10:58:54 AM EDT 
//


package com.vidyo.parser.xsd.vr2config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VRConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VRConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RouterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CMCPAddressList" type="{http://www.vidyo.com/vr2configparser.xsd}CMCPAddressListType"/>
 *         &lt;element name="VidyoManagerAccess" type="{http://www.vidyo.com/vr2configparser.xsd}VMAccessType"/>
 *         &lt;element name="ListenVMList" type="{http://www.vidyo.com/vr2configparser.xsd}ListenVMListType"/>
 *         &lt;element name="ConnectVMList" type="{http://www.vidyo.com/vr2configparser.xsd}ConnectVMListType"/>
 *         &lt;element name="MediaAddressMap" type="{http://www.vidyo.com/vr2configparser.xsd}MediaAddressMapType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StunServerAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MediaPortRange" type="{http://www.vidyo.com/vr2configparser.xsd}MediaPortRangeType" minOccurs="0"/>
 *         &lt;element name="SecurityEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="VideoPrecedence" type="{http://www.vidyo.com/vr2configparser.xsd}MediaStreamPrecedenceType" minOccurs="0"/>
 *         &lt;element name="AudioPrecedence" type="{http://www.vidyo.com/vr2configparser.xsd}MediaStreamPrecedenceType" minOccurs="0"/>
 *         &lt;element name="AppPrecedence" type="{http://www.vidyo.com/vr2configparser.xsd}MediaStreamPrecedenceType" minOccurs="0"/>
 *         &lt;element name="SignalingPrecedence" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="ProxyEnable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ProxyCompatibility" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ProxyUseTls" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LogFileHistoryDays" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="LogFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LogLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxLogFileSizeKB" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="Stat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfThreads" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VRConfigType", propOrder = {
    "documentVersion",
    "routerName",
    "cmcpAddressList",
    "vidyoManagerAccess",
    "listenVMList",
    "connectVMList",
    "mediaAddressMap",
    "stunServerAddress",
    "mediaPortRange",
    "securityEnabled",
    "videoPrecedence",
    "audioPrecedence",
    "appPrecedence",
    "signalingPrecedence",
    "proxyEnable",
    "proxyCompatibility",
    "proxyUseTls",
    "logFileHistoryDays",
    "logFileName",
    "logLevel",
    "maxLogFileSizeKB",
    "stat",
    "numberOfThreads",
    "any"
})
public class VRConfigType {

    @XmlElement(name = "DocumentVersion", required = true)
    protected String documentVersion;
    @XmlElement(name = "RouterName", required = true)
    protected String routerName;
    @XmlElement(name = "CMCPAddressList", required = true)
    protected CMCPAddressListType cmcpAddressList;
    @XmlElement(name = "VidyoManagerAccess", required = true)
    protected VMAccessType vidyoManagerAccess;
    @XmlElement(name = "ListenVMList", required = true)
    protected ListenVMListType listenVMList;
    @XmlElement(name = "ConnectVMList", required = true)
    protected ConnectVMListType connectVMList;
    @XmlElement(name = "MediaAddressMap")
    protected List<MediaAddressMapType> mediaAddressMap;
    @XmlElement(name = "StunServerAddress")
    protected String stunServerAddress;
    @XmlElement(name = "MediaPortRange")
    protected MediaPortRangeType mediaPortRange;
    @XmlElement(name = "SecurityEnabled")
    protected Boolean securityEnabled;
    @XmlElement(name = "VideoPrecedence")
    protected MediaStreamPrecedenceType videoPrecedence;
    @XmlElement(name = "AudioPrecedence")
    protected MediaStreamPrecedenceType audioPrecedence;
    @XmlElement(name = "AppPrecedence")
    protected MediaStreamPrecedenceType appPrecedence;
    @XmlElement(name = "SignalingPrecedence")
    @XmlSchemaType(name = "unsignedInt")
    protected Long signalingPrecedence;
    @XmlElement(name = "ProxyEnable")
    protected Boolean proxyEnable;
    @XmlElement(name = "ProxyCompatibility")
    protected Boolean proxyCompatibility;
    @XmlElement(name = "ProxyUseTls")
    protected Boolean proxyUseTls;
    @XmlElement(name = "LogFileHistoryDays")
    @XmlSchemaType(name = "unsignedInt")
    protected Long logFileHistoryDays;
    @XmlElement(name = "LogFileName")
    protected String logFileName;
    @XmlElement(name = "LogLevel")
    protected String logLevel;
    @XmlElement(name = "MaxLogFileSizeKB")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxLogFileSizeKB;
    @XmlElement(name = "Stat", required = true)
    protected String stat;
    @XmlElement(name = "NumberOfThreads")
    @XmlSchemaType(name = "unsignedInt")
    protected long numberOfThreads;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the documentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentVersion() {
        return documentVersion;
    }

    /**
     * Sets the value of the documentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentVersion(String value) {
        this.documentVersion = value;
    }

    /**
     * Gets the value of the routerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouterName() {
        return routerName;
    }

    /**
     * Sets the value of the routerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouterName(String value) {
        this.routerName = value;
    }

    /**
     * Gets the value of the cmcpAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link CMCPAddressListType }
     *     
     */
    public CMCPAddressListType getCMCPAddressList() {
        return cmcpAddressList;
    }

    /**
     * Sets the value of the cmcpAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CMCPAddressListType }
     *     
     */
    public void setCMCPAddressList(CMCPAddressListType value) {
        this.cmcpAddressList = value;
    }

    /**
     * Gets the value of the vidyoManagerAccess property.
     * 
     * @return
     *     possible object is
     *     {@link VMAccessType }
     *     
     */
    public VMAccessType getVidyoManagerAccess() {
        return vidyoManagerAccess;
    }

    /**
     * Sets the value of the vidyoManagerAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link VMAccessType }
     *     
     */
    public void setVidyoManagerAccess(VMAccessType value) {
        this.vidyoManagerAccess = value;
    }

    /**
     * Gets the value of the listenVMList property.
     * 
     * @return
     *     possible object is
     *     {@link ListenVMListType }
     *     
     */
    public ListenVMListType getListenVMList() {
        return listenVMList;
    }

    /**
     * Sets the value of the listenVMList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListenVMListType }
     *     
     */
    public void setListenVMList(ListenVMListType value) {
        this.listenVMList = value;
    }

    /**
     * Gets the value of the connectVMList property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectVMListType }
     *     
     */
    public ConnectVMListType getConnectVMList() {
        return connectVMList;
    }

    /**
     * Sets the value of the connectVMList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectVMListType }
     *     
     */
    public void setConnectVMList(ConnectVMListType value) {
        this.connectVMList = value;
    }

    /**
     * Gets the value of the mediaAddressMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mediaAddressMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMediaAddressMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MediaAddressMapType }
     * 
     * 
     */
    public List<MediaAddressMapType> getMediaAddressMap() {
        if (mediaAddressMap == null) {
            mediaAddressMap = new ArrayList<MediaAddressMapType>();
        }
        return this.mediaAddressMap;
    }

    /**
     * Gets the value of the stunServerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStunServerAddress() {
        return stunServerAddress;
    }

    /**
     * Sets the value of the stunServerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStunServerAddress(String value) {
        this.stunServerAddress = value;
    }

    /**
     * Gets the value of the mediaPortRange property.
     * 
     * @return
     *     possible object is
     *     {@link MediaPortRangeType }
     *     
     */
    public MediaPortRangeType getMediaPortRange() {
        return mediaPortRange;
    }

    /**
     * Sets the value of the mediaPortRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaPortRangeType }
     *     
     */
    public void setMediaPortRange(MediaPortRangeType value) {
        this.mediaPortRange = value;
    }

    /**
     * Gets the value of the securityEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSecurityEnabled() {
        return securityEnabled;
    }

    /**
     * Sets the value of the securityEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSecurityEnabled(Boolean value) {
        this.securityEnabled = value;
    }

    /**
     * Gets the value of the videoPrecedence property.
     * 
     * @return
     *     possible object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public MediaStreamPrecedenceType getVideoPrecedence() {
        return videoPrecedence;
    }

    /**
     * Sets the value of the videoPrecedence property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public void setVideoPrecedence(MediaStreamPrecedenceType value) {
        this.videoPrecedence = value;
    }

    /**
     * Gets the value of the audioPrecedence property.
     * 
     * @return
     *     possible object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public MediaStreamPrecedenceType getAudioPrecedence() {
        return audioPrecedence;
    }

    /**
     * Sets the value of the audioPrecedence property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public void setAudioPrecedence(MediaStreamPrecedenceType value) {
        this.audioPrecedence = value;
    }

    /**
     * Gets the value of the appPrecedence property.
     * 
     * @return
     *     possible object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public MediaStreamPrecedenceType getAppPrecedence() {
        return appPrecedence;
    }

    /**
     * Sets the value of the appPrecedence property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaStreamPrecedenceType }
     *     
     */
    public void setAppPrecedence(MediaStreamPrecedenceType value) {
        this.appPrecedence = value;
    }

    /**
     * Gets the value of the signalingPrecedence property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSignalingPrecedence() {
        return signalingPrecedence;
    }

    /**
     * Sets the value of the signalingPrecedence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSignalingPrecedence(Long value) {
        this.signalingPrecedence = value;
    }

    /**
     * Gets the value of the proxyEnable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProxyEnable() {
        return proxyEnable;
    }

    /**
     * Sets the value of the proxyEnable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProxyEnable(Boolean value) {
        this.proxyEnable = value;
    }

    /**
     * Gets the value of the proxyCompatibility property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProxyCompatibility() {
        return proxyCompatibility;
    }

    /**
     * Sets the value of the proxyCompatibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProxyCompatibility(Boolean value) {
        this.proxyCompatibility = value;
    }

    /**
     * Gets the value of the proxyUseTls property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProxyUseTls() {
        return proxyUseTls;
    }

    /**
     * Sets the value of the proxyUseTls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProxyUseTls(Boolean value) {
        this.proxyUseTls = value;
    }

    /**
     * Gets the value of the logFileHistoryDays property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLogFileHistoryDays() {
        return logFileHistoryDays;
    }

    /**
     * Sets the value of the logFileHistoryDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLogFileHistoryDays(Long value) {
        this.logFileHistoryDays = value;
    }

    /**
     * Gets the value of the logFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogFileName() {
        return logFileName;
    }

    /**
     * Sets the value of the logFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogFileName(String value) {
        this.logFileName = value;
    }

    /**
     * Gets the value of the logLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogLevel() {
        return logLevel;
    }

    /**
     * Sets the value of the logLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogLevel(String value) {
        this.logLevel = value;
    }

    /**
     * Gets the value of the maxLogFileSizeKB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxLogFileSizeKB() {
        return maxLogFileSizeKB;
    }

    /**
     * Sets the value of the maxLogFileSizeKB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxLogFileSizeKB(Long value) {
        this.maxLogFileSizeKB = value;
    }

    /**
     * Gets the value of the stat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStat() {
        return stat;
    }

    /**
     * Sets the value of the stat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStat(String value) {
        this.stat = value;
    }

    /**
     * Gets the value of the numberOfThreads property.
     * 
     */
    public long getNumberOfThreads() {
        return numberOfThreads;
    }

    /**
     * Sets the value of the numberOfThreads property.
     * 
     */
    public void setNumberOfThreads(long value) {
        this.numberOfThreads = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
