//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 11:24:41 AM IST 
//


package com.vidyo.parser.xsd.networkconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BandwidthMapElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BandwidthMapElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FromRouterGroupID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ToRouterGroupID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WeightedBandwidth">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ConnDirection" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="None"/>
 *               &lt;enumeration value="ToDest"/>
 *               &lt;enumeration value="FromDest"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BandwidthMapElementType", propOrder = {
    "fromRouterGroupID",
    "toRouterGroupID",
    "weightedBandwidth",
    "connDirection"
})
public class BandwidthMapElementType {

    @XmlElement(name = "FromRouterGroupID", required = true)
    protected String fromRouterGroupID;
    @XmlElement(name = "ToRouterGroupID", required = true)
    protected String toRouterGroupID;
    @XmlElement(name = "WeightedBandwidth")
    protected long weightedBandwidth;
    @XmlElement(name = "ConnDirection")
    protected String connDirection;

    /**
     * Gets the value of the fromRouterGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromRouterGroupID() {
        return fromRouterGroupID;
    }

    /**
     * Sets the value of the fromRouterGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromRouterGroupID(String value) {
        this.fromRouterGroupID = value;
    }

    /**
     * Gets the value of the toRouterGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToRouterGroupID() {
        return toRouterGroupID;
    }

    /**
     * Sets the value of the toRouterGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToRouterGroupID(String value) {
        this.toRouterGroupID = value;
    }

    /**
     * Gets the value of the weightedBandwidth property.
     * 
     */
    public long getWeightedBandwidth() {
        return weightedBandwidth;
    }

    /**
     * Sets the value of the weightedBandwidth property.
     * 
     */
    public void setWeightedBandwidth(long value) {
        this.weightedBandwidth = value;
    }

    /**
     * Gets the value of the connDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnDirection() {
        return connDirection;
    }

    /**
     * Sets the value of the connDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnDirection(String value) {
        this.connDirection = value;
    }

}
