//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 11:24:41 AM IST 
//


package com.vidyo.parser.xsd.networkconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IPV4AddressRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPV4AddressRangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Candidate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPAddrLow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPAddrHigh" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPV4AddressRangeType", propOrder = {
    "candidate",
    "ipAddrLow",
    "ipAddrHigh"
})
public class IPV4AddressRangeType {

    @XmlElement(name = "Candidate", required = true)
    protected String candidate;
    @XmlElement(name = "IPAddrLow", required = true)
    protected String ipAddrLow;
    @XmlElement(name = "IPAddrHigh", required = true)
    protected String ipAddrHigh;

    /**
     * Gets the value of the candidate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCandidate() {
        return candidate;
    }

    /**
     * Sets the value of the candidate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCandidate(String value) {
        this.candidate = value;
    }

    /**
     * Gets the value of the ipAddrLow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPAddrLow() {
        return ipAddrLow;
    }

    /**
     * Sets the value of the ipAddrLow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPAddrLow(String value) {
        this.ipAddrLow = value;
    }

    /**
     * Gets the value of the ipAddrHigh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPAddrHigh() {
        return ipAddrHigh;
    }

    /**
     * Sets the value of the ipAddrHigh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPAddrHigh(String value) {
        this.ipAddrHigh = value;
    }

}
