//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 11:24:41 AM IST 
//


package com.vidyo.parser.xsd.networkconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RuleSet" type="{http://www.vidyo.com/NetConfigParser.xsd}RuleSetType"/>
 *         &lt;element name="PrioritizedGroupLists" type="{http://www.vidyo.com/NetConfigParser.xsd}PrioritizedGroupListsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationType", propOrder = {
    "id",
    "name",
    "ruleSet",
    "prioritizedGroupLists"
})
public class LocationType {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "RuleSet", required = true)
    protected RuleSetType ruleSet;
    @XmlElement(name = "PrioritizedGroupLists", required = true)
    protected PrioritizedGroupListsType prioritizedGroupLists;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the ruleSet property.
     * 
     * @return
     *     possible object is
     *     {@link RuleSetType }
     *     
     */
    public RuleSetType getRuleSet() {
        return ruleSet;
    }

    /**
     * Sets the value of the ruleSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleSetType }
     *     
     */
    public void setRuleSet(RuleSetType value) {
        this.ruleSet = value;
    }

    /**
     * Gets the value of the prioritizedGroupLists property.
     * 
     * @return
     *     possible object is
     *     {@link PrioritizedGroupListsType }
     *     
     */
    public PrioritizedGroupListsType getPrioritizedGroupLists() {
        return prioritizedGroupLists;
    }

    /**
     * Sets the value of the prioritizedGroupLists property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrioritizedGroupListsType }
     *     
     */
    public void setPrioritizedGroupLists(PrioritizedGroupListsType value) {
        this.prioritizedGroupLists = value;
    }

}
