//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 11:24:41 AM IST 
//


package com.vidyo.parser.xsd.networkconfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NetworkElement" type="{http://www.vidyo.com/NetConfigParser.xsd}NetworkElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Categories" type="{http://www.vidyo.com/NetConfigParser.xsd}CategoriesType"/>
 *         &lt;element name="Group" type="{http://www.vidyo.com/NetConfigParser.xsd}GroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LocationCandidates" type="{http://www.vidyo.com/NetConfigParser.xsd}Candidates"/>
 *         &lt;element name="Location" type="{http://www.vidyo.com/NetConfigParser.xsd}LocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BandwidthMap" type="{http://www.vidyo.com/NetConfigParser.xsd}BandwidthMapType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkConfigType", propOrder = {
    "documentVersion",
    "networkElement",
    "categories",
    "group",
    "locationCandidates",
    "location",
    "bandwidthMap"
})
public class NetworkConfigType {

    @XmlElement(name = "DocumentVersion", required = true)
    protected String documentVersion;
    @XmlElement(name = "NetworkElement")
    protected List<NetworkElement> networkElement;
    @XmlElement(name = "Categories", required = true)
    protected CategoriesType categories;
    @XmlElement(name = "Group")
    protected List<GroupType> group;
    @XmlElement(name = "LocationCandidates", required = true)
    protected Candidates locationCandidates;
    @XmlElement(name = "Location")
    protected List<LocationType> location;
    @XmlElement(name = "BandwidthMap")
    protected BandwidthMapType bandwidthMap;

    /**
     * Gets the value of the documentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentVersion() {
        return documentVersion;
    }

    /**
     * Sets the value of the documentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentVersion(String value) {
        this.documentVersion = value;
    }

    /**
     * Gets the value of the networkElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the networkElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkElement }
     * 
     * 
     */
    public List<NetworkElement> getNetworkElement() {
        if (networkElement == null) {
            networkElement = new ArrayList<NetworkElement>();
        }
        return this.networkElement;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link CategoriesType }
     *     
     */
    public CategoriesType getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoriesType }
     *     
     */
    public void setCategories(CategoriesType value) {
        this.categories = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupType }
     * 
     * 
     */
    public List<GroupType> getGroup() {
        if (group == null) {
            group = new ArrayList<GroupType>();
        }
        return this.group;
    }

    /**
     * Gets the value of the locationCandidates property.
     * 
     * @return
     *     possible object is
     *     {@link Candidates }
     *     
     */
    public Candidates getLocationCandidates() {
        return locationCandidates;
    }

    /**
     * Sets the value of the locationCandidates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Candidates }
     *     
     */
    public void setLocationCandidates(Candidates value) {
        this.locationCandidates = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationType }
     * 
     * 
     */
    public List<LocationType> getLocation() {
        if (location == null) {
            location = new ArrayList<LocationType>();
        }
        return this.location;
    }

    /**
     * Gets the value of the bandwidthMap property.
     * 
     * @return
     *     possible object is
     *     {@link BandwidthMapType }
     *     
     */
    public BandwidthMapType getBandwidthMap() {
        return bandwidthMap;
    }

    /**
     * Sets the value of the bandwidthMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link BandwidthMapType }
     *     
     */
    public void setBandwidthMap(BandwidthMapType value) {
        this.bandwidthMap = value;
    }

}
