//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.04 at 04:43:02 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.vidyo.com/notification", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vidyo.service.statusnotify.types;
