//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.13 at 12:07:58 PM EDT 
//


package com.vidyo.parser.xml.vmconfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VMConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VMConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IPAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SOAPAddressList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SOAPListenAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EMCPAddressList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EMCPListenAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RMCPAddressList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RMCPListenAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="VidyoPortalAddressList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VidyoPortalConnectAddress" type="{}vpURI" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SecurityEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DatabaseConfig">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DBAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OdbcDSN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OdbcType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OdbcUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OdbcPwd" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LogFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LogLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxLogFileSizeKB" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="LogFileHistoryDays" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="Stat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfThreads" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="SignalingPrecedence" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VMConfigType", propOrder = {
    "documentVersion",
    "ipAddress",
    "soapAddressList",
    "emcpAddressList",
    "rmcpAddressList",
    "vidyoPortalAddressList",
    "securityEnabled",
    "databaseConfig",
    "logFileName",
    "logLevel",
    "maxLogFileSizeKB",
    "logFileHistoryDays",
    "stat",
    "numberOfThreads",
    "signalingPrecedence"
})
public class VMConfigType {

    @XmlElement(name = "DocumentVersion", required = true)
    protected String documentVersion;
    @XmlElement(name = "IPAddress")
    protected String ipAddress;
    @XmlElement(name = "SOAPAddressList", required = true)
    protected VMConfigType.SOAPAddressList soapAddressList;
    @XmlElement(name = "EMCPAddressList", required = true)
    protected VMConfigType.EMCPAddressList emcpAddressList;
    @XmlElement(name = "RMCPAddressList", required = true)
    protected VMConfigType.RMCPAddressList rmcpAddressList;
    @XmlElement(name = "VidyoPortalAddressList", required = true)
    protected VMConfigType.VidyoPortalAddressList vidyoPortalAddressList;
    @XmlElement(name = "SecurityEnabled")
    protected Boolean securityEnabled;
    @XmlElement(name = "DatabaseConfig", required = true)
    protected VMConfigType.DatabaseConfig databaseConfig;
    @XmlElement(name = "LogFileName")
    protected String logFileName;
    @XmlElement(name = "LogLevel")
    protected String logLevel;
    @XmlElement(name = "MaxLogFileSizeKB")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxLogFileSizeKB;
    @XmlElement(name = "LogFileHistoryDays")
    @XmlSchemaType(name = "unsignedInt")
    protected Long logFileHistoryDays;
    @XmlElement(name = "Stat", required = true)
    protected String stat;
    @XmlElement(name = "NumberOfThreads")
    @XmlSchemaType(name = "unsignedInt")
    protected long numberOfThreads;
    @XmlElement(name = "SignalingPrecedence")
    @XmlSchemaType(name = "unsignedInt")
    protected Long signalingPrecedence;

    /**
     * Gets the value of the documentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentVersion() {
        return documentVersion;
    }

    /**
     * Sets the value of the documentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentVersion(String value) {
        this.documentVersion = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the soapAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link VMConfigType.SOAPAddressList }
     *     
     */
    public VMConfigType.SOAPAddressList getSOAPAddressList() {
        return soapAddressList;
    }

    /**
     * Sets the value of the soapAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VMConfigType.SOAPAddressList }
     *     
     */
    public void setSOAPAddressList(VMConfigType.SOAPAddressList value) {
        this.soapAddressList = value;
    }

    /**
     * Gets the value of the emcpAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link VMConfigType.EMCPAddressList }
     *     
     */
    public VMConfigType.EMCPAddressList getEMCPAddressList() {
        return emcpAddressList;
    }

    /**
     * Sets the value of the emcpAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VMConfigType.EMCPAddressList }
     *     
     */
    public void setEMCPAddressList(VMConfigType.EMCPAddressList value) {
        this.emcpAddressList = value;
    }

    /**
     * Gets the value of the rmcpAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link VMConfigType.RMCPAddressList }
     *     
     */
    public VMConfigType.RMCPAddressList getRMCPAddressList() {
        return rmcpAddressList;
    }

    /**
     * Sets the value of the rmcpAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VMConfigType.RMCPAddressList }
     *     
     */
    public void setRMCPAddressList(VMConfigType.RMCPAddressList value) {
        this.rmcpAddressList = value;
    }

    /**
     * Gets the value of the vidyoPortalAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link VMConfigType.VidyoPortalAddressList }
     *     
     */
    public VMConfigType.VidyoPortalAddressList getVidyoPortalAddressList() {
        return vidyoPortalAddressList;
    }

    /**
     * Sets the value of the vidyoPortalAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VMConfigType.VidyoPortalAddressList }
     *     
     */
    public void setVidyoPortalAddressList(VMConfigType.VidyoPortalAddressList value) {
        this.vidyoPortalAddressList = value;
    }

    /**
     * Gets the value of the securityEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSecurityEnabled() {
        return securityEnabled;
    }

    /**
     * Sets the value of the securityEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSecurityEnabled(Boolean value) {
        this.securityEnabled = value;
    }

    /**
     * Gets the value of the databaseConfig property.
     * 
     * @return
     *     possible object is
     *     {@link VMConfigType.DatabaseConfig }
     *     
     */
    public VMConfigType.DatabaseConfig getDatabaseConfig() {
        return databaseConfig;
    }

    /**
     * Sets the value of the databaseConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link VMConfigType.DatabaseConfig }
     *     
     */
    public void setDatabaseConfig(VMConfigType.DatabaseConfig value) {
        this.databaseConfig = value;
    }

    /**
     * Gets the value of the logFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogFileName() {
        return logFileName;
    }

    /**
     * Sets the value of the logFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogFileName(String value) {
        this.logFileName = value;
    }

    /**
     * Gets the value of the logLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogLevel() {
        return logLevel;
    }

    /**
     * Sets the value of the logLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogLevel(String value) {
        this.logLevel = value;
    }

    /**
     * Gets the value of the maxLogFileSizeKB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxLogFileSizeKB() {
        return maxLogFileSizeKB;
    }

    /**
     * Sets the value of the maxLogFileSizeKB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxLogFileSizeKB(Long value) {
        this.maxLogFileSizeKB = value;
    }

    /**
     * Gets the value of the logFileHistoryDays property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLogFileHistoryDays() {
        return logFileHistoryDays;
    }

    /**
     * Sets the value of the logFileHistoryDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLogFileHistoryDays(Long value) {
        this.logFileHistoryDays = value;
    }

    /**
     * Gets the value of the stat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStat() {
        return stat;
    }

    /**
     * Sets the value of the stat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStat(String value) {
        this.stat = value;
    }

    /**
     * Gets the value of the numberOfThreads property.
     * 
     */
    public long getNumberOfThreads() {
        return numberOfThreads;
    }

    /**
     * Sets the value of the numberOfThreads property.
     * 
     */
    public void setNumberOfThreads(long value) {
        this.numberOfThreads = value;
    }

    /**
     * Gets the value of the signalingPrecedence property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSignalingPrecedence() {
        return signalingPrecedence;
    }

    /**
     * Sets the value of the signalingPrecedence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSignalingPrecedence(Long value) {
        this.signalingPrecedence = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DBAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OdbcDSN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OdbcType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OdbcUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OdbcPwd" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dbAddress",
        "odbcDSN",
        "odbcType",
        "odbcUID",
        "odbcPwd"
    })
    public static class DatabaseConfig {

        @XmlElement(name = "DBAddress", required = true)
        protected String dbAddress;
        @XmlElement(name = "OdbcDSN", required = true)
        protected String odbcDSN;
        @XmlElement(name = "OdbcType", required = true)
        protected String odbcType;
        @XmlElement(name = "OdbcUID", required = true)
        protected String odbcUID;
        @XmlElement(name = "OdbcPwd", required = true)
        protected byte[] odbcPwd;

        /**
         * Gets the value of the dbAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDBAddress() {
            return dbAddress;
        }

        /**
         * Sets the value of the dbAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDBAddress(String value) {
            this.dbAddress = value;
        }

        /**
         * Gets the value of the odbcDSN property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOdbcDSN() {
            return odbcDSN;
        }

        /**
         * Sets the value of the odbcDSN property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOdbcDSN(String value) {
            this.odbcDSN = value;
        }

        /**
         * Gets the value of the odbcType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOdbcType() {
            return odbcType;
        }

        /**
         * Sets the value of the odbcType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOdbcType(String value) {
            this.odbcType = value;
        }

        /**
         * Gets the value of the odbcUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOdbcUID() {
            return odbcUID;
        }

        /**
         * Sets the value of the odbcUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOdbcUID(String value) {
            this.odbcUID = value;
        }

        /**
         * Gets the value of the odbcPwd property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getOdbcPwd() {
            return odbcPwd;
        }

        /**
         * Sets the value of the odbcPwd property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setOdbcPwd(byte[] value) {
            this.odbcPwd = ((byte[]) value);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EMCPListenAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "emcpListenAddress"
    })
    public static class EMCPAddressList {

        @XmlElement(name = "EMCPListenAddress")
        protected List<String> emcpListenAddress;

        /**
         * Gets the value of the emcpListenAddress property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the emcpListenAddress property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEMCPListenAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getEMCPListenAddress() {
            if (emcpListenAddress == null) {
                emcpListenAddress = new ArrayList<String>();
            }
            return this.emcpListenAddress;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RMCPListenAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rmcpListenAddress"
    })
    public static class RMCPAddressList {

        @XmlElement(name = "RMCPListenAddress")
        protected List<String> rmcpListenAddress;

        /**
         * Gets the value of the rmcpListenAddress property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rmcpListenAddress property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRMCPListenAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRMCPListenAddress() {
            if (rmcpListenAddress == null) {
                rmcpListenAddress = new ArrayList<String>();
            }
            return this.rmcpListenAddress;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SOAPListenAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "soapListenAddress"
    })
    public static class SOAPAddressList {

        @XmlElement(name = "SOAPListenAddress", required = true)
        protected List<String> soapListenAddress;

        /**
         * Gets the value of the soapListenAddress property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the soapListenAddress property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSOAPListenAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSOAPListenAddress() {
            if (soapListenAddress == null) {
                soapListenAddress = new ArrayList<String>();
            }
            return this.soapListenAddress;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="VidyoPortalConnectAddress" type="{}vpURI" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vidyoPortalConnectAddress"
    })
    public static class VidyoPortalAddressList {

        @XmlElement(name = "VidyoPortalConnectAddress")
        protected List<VpURI> vidyoPortalConnectAddress;

        /**
         * Gets the value of the vidyoPortalConnectAddress property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vidyoPortalConnectAddress property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVidyoPortalConnectAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VpURI }
         * 
         * 
         */
        public List<VpURI> getVidyoPortalConnectAddress() {
            if (vidyoPortalConnectAddress == null) {
                vidyoPortalConnectAddress = new ArrayList<VpURI>();
            }
            return this.vidyoPortalConnectAddress;
        }

    }

}
