package com.vidyo.service.configuration.enums;

public enum LegacyTenantConfigurationEnum {

	// README : Any new Tenant Configuration added to the table Configuration
	// should be added here as well
	// Maintain the config names in alphabetical order
	AboutInfo,
	AuthenticationFlag,
	AuthenticationPassword,
	AuthenticationURL,
	AuthenticationUsername,
	CACAuthenticationFlag,
	CACAuthenticationType,
	CACLDAPAuthenticationBase,
	CACLDAPAuthenticationFilter,
	CACLDAPAuthenticationFlag,
	CACLDAPAuthenticationPassword,
	CACLDAPAuthenticationScope,
	CACLDAPAuthenticationURL,
	CACLDAPAuthenticationUsername,
	CACNonceCheck,
	CACOCSPDirtyFlag,
	CACOCSPResponderCheck,
	CACOCSPResponderText,
	CACOCSPRevocationCheck,
	ContactInfo,
	DefaultLocationTagID,
	DSCP_MEDIA_AUDIO,
	DSCP_MEDIA_DATA,
	DSCP_MEDIA_VIDEO,
	DSCP_SIGNALING,
	EnableEpic,
	EnableNewAccountNotification,
	GuestGroupID,
	GuestLocationID,
	GuestLogin,
	GuestProxyID,
	InvitationEmailContent,
	InvitationEmailContentHtml,
	InvitationEmailSubject,
	LDAPAuthenticationAttributeMappingFlag,
	LDAPAuthenticationBase,
	LDAPAuthenticationFilter,
	LDAPAuthenticationFlag,
	LDAPAuthenticationPassword,
	LDAPAuthenticationScope,
	LDAPAuthenticationURL,
	LDAPAuthenticationUsername,
	logo,
	logoImage,
	NotificationEmailFrom,
	NotificationEmailTo,
	NumExecutives,
	NumInstalls,
	NumPanoramas,
	NumPorts,
	NumSeats,
	REQUEST_SIGNED,
	RestAuthenticationFlag,
	RestAuthenticationURL,
	SAML_AUTH_FLAG,
	SAML_AUTH_PROVISION_TYPE,
	SAML_IDP_ATTRIBUTE_FOR_USERNAME,
	SAML_IDP_METADATA,
	SAML_SP_ENTITY_ID,
	SAML_SP_PROTOCOL,
	SAML_SP_SECURITY_PROFILE,
	SAML_SP_SIGN_METADATA,
	SAML_SP_SSL_PROFILE,
	SharedSecret,
	SystemLanguage,
	VidyoWebEnabled,
	VoiceOnlyContent,
	WANT_ASSERTION_ASSIGNED,
	WebcastContent

}
