package com.vidyo.service.configuration.enums;

public enum TenantConfigurationEnum {

	// README : Any new column added to the TenantConfiguration table should be
	// added here as well
	// Maintain the config names in alphabetical order
	alwaysUseProxy,
	androidAppLink,
	androidPackageName,
	createPublicRoomEnable,
	desktopProtocol,
	endpointBehavior,
	endpointPrivateChat,
	endpointPublicChat,
	endpointUploadMode,
	externalIntegrationMode,
	externalNotificationUrl,
	externalPassword,
	externalUsername,
	extIntegrationSharedSecret,	
	extnLength,
	iOSAppId,
	iOSAppLink,
	iOSBundleId,
	lectureModeAllowed,
	lectureModeStrict,
	logAggregation,
	maxCreatePublicRoomTenant,
	maxCreatePublicRoomUser,
	maxMediaPort,
	minMediaPort,
	minPINLength,
	mobileProtocol,
	personalRoom,
	pp,
	ppVersion,
	roomCountThreshold,
	sessionExpirationPeriod,
	tc,
	tcVersion,
	testCall,
	tytoIntegrationMode,
	tytoPassword,
	tytoUrl,
	tytoUsername,
	uploadUserImage,
	userImage,
	vidyoNeoWebRTCGuestEnabled,
	vidyoNeoWebRTCUserEnabled,
	vidyoNotificationUrl,
	vidyoPassword,
	vidyoUsername,
	waitingRoomsEnabled,
	waitUntilOwnerJoins,
	zincEnabled,
	zincUrl
}
